modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="darkdoppelganger"
mandatory=true
versionRange="${dark_doppelganger_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="ageofmythology"
mandatory=true
versionRange="${age_of_mythology_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="bettermorph"
mandatory=true
versionRange="${better_morph_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="irons_spellbooks"
mandatory=true
versionRange="${irons_spellbooks_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="geckolib"
mandatory=true
versionRange="${geckolib_version_range}"
ordering="AFTER"
side="BOTH"
